### ISSUE TITLE
Crash when adding a section before view appears

### ISSUE THREAD

**Issue by JosephDuffy** [composed-swift/ComposedUI#8]
# Describe the bug

When adding a section to a `ComposedSectionProvider` in a `viewDidLoad` _after_ the `CollectionCoordinator` has been set as the delegate but _before_ the view has appeared the coordinator will `fatalError` in `elementsProvider(for:)` with error `Fatal error: No UI configuration available for section 2`.

# To Reproduce

1. Checkout https://github.com/composed-swift/Composed-Demo/tree/ComposedSectionProvider-crash-example
2. Uncomment https://github.com/composed-swift/Composed-Demo/blob/ComposedSectionProvider-crash-example/Composed-Demo/Collection/PeopleCollectionViewController.swift#L20

# Expected behavior

Should not crash

# Environment

 - OS Version: iOS 13.5, iOS 14 beta 7
 - Library Version: 1.0.2
 - Device: iPhone 8 Simulator

# Additional context

The crash is triggered by `collectionView.performBatchUpdates`, but the closure is never executed so `prepareSections` never gets a chance to be called.

**Comment by shaps80** [comment]
Any suggested fix? I kinda get the issue, but I'm not sure off-hand the most appropriate fix. Seems we'd need to know somehow that its 'detached'? Or perhaps I'm misunderstand the issue?

**Comment by shaps80** [comment]
Is this resolved from the PR I just merged related to `performBatchUpdates` or is this a separate issue?

**Comment by JosephDuffy** [comment]
> Is this resolved from the PR I just merged related to `performBatchUpdates` or is this a separate issue?

I tried the change but it didn't fix this. It could be something similar though so worth thinking about.
